### PR TITLE
Animations + Clean Up

### PR DESCRIPTION
**Pull request by neetjn**
Following my previous changes for more efficient update cycles, I've made the deployments component self contained so all components no longer access the global scope and operate exclusively via data passed through opts.

I've optimized the pagination processor to make sure data isn't being binded and triggering updates.

As for animations, I implemented animate.css for basic transitions showing how Riot.js plays well with plain css transitions due to the mounting logic. I've also added a basic example for using animore in the oversight view.

The home page views have been removed from the routes subdirectory to ward any confusion.

Components exercising Chart.js also now destroy their any previously rendered charts prior to redrawing them to avoid any issues with overlapping graphics.

### CODE REVIEW

**Comment by captchadex** [comment]
Should we remove the unnecessary self = this in the components?

**Comment by neetjn** [comment]
Anywhere it's not necessary, yes, I can take care of that when I clock out of the office. That being stated, I just default to this as a habbit as to not mix my context, and be sure I'm referencing my tag appropriately.

ie; https://jsfiddle.net/neetjn/09numv9g/

That being stated, with the latest string of updates it shouldn't be required anywhere but the home views.

**Comment by neetjn** [comment]
Got home and did a double take on each component, every component that doesn't require closure assist is already using `this`. I'm only using `self` in components that require context management due to closure.

I'm going to assume any javascript developers going through our example app would also know about javascript closure.

**Comment by captchadex** [comment]
Sure sounds good. I only did a quick skim while looking for examples for my section :)

**Pull request merged**
