### PR TITLE
Initial Boilerplate

### PR DESCRIPTION
**Pull request by neetjn**
Just a boilerplate I wrote up last night, has:
- a tag w/ a test using karma and mocha
- root tag
- webpack config w/ dev middleware (so we can setup ssr)
- basic eslint and editorconfig (subject to change depending on the team's preferences)
- basic travis config (wasn't sure what ci system we'd be using)
- bulma styling w/ bulmaswatch superhero theme: https://jenil.github.io/bulmaswatch/
  - subject to change

Used a pretty generic project setup, can be changed as seen fit.

### CODE REVIEW

**Comment by neetjn** [comment]
Didn't implement routing because I didn't know what router the team wanted to use.

**Comment by neetjn** [comment]
For styling I just used the Sass, CSS, and style loaders. I didn't know if anyone had a preference as to whether or not to use the extract text plugin.

**Comment by NukaPunk** [comment]
Sass is pretty widely adopted so I'm fine with it. Webpack Dev server makes sense, for the same reason. 

Looks good to me.

**Comment by jimsparkman** [comment]
Go ahead and merge this?

**Pull request merged**
